<?php

/**
 * @author     Lars Kristian Dahl <http://www.krisd.com>
 * @copyright  Copyright (c) 2011 Lars Kristian Dahl <http://www.krisd.com>
 * @license    http://www.apache.org/licenses/LICENSE-2.0
 * @version    SVN: $Id$
 */
use ezmvc\lib\html;
?>

<br/>eZ-library catalogues your books online. It's easy, fast and FREE!
<br/>
<br/>
CHECK THIS OUT:<br/>
<ul>
    <li>Store thousands of books for free.</li>
    <li>Automatically look up data based on ISBN.</li>
    <li>Live search through all your books.</li>
    <li>Complex filtering of all meta data.</li>
    <li>Categorize and tags your books.</li>
    <li>and MORE.</li>
</ul>

Sign up <?php echo Html::link('user/register', 'HERE'); ?>, or if you already own an account <?php echo Html::link('user/login', 'LOGIN'); ?>!
<br/><br/>
For a LIVE demo, log in with username: 'user' and password: 'user'.

